name: Validate code

on:
  workflow_call:
    inputs:
      npm-script-name-lint:
        description: Name of the NPM script that linters the code
        type: string
        required: false
        default: lint
      npm-script-name-test:
        description: Name of the NPM script that runs tests
        type: string
        required: false
        default: test
      npm-script-name-ts-validate:
        description: Name of the NPM script that validates typescript code integrity (tries to build app from TS sources)
        type: string
        required: false
        default: ts:validate
      private-npm-registry-scope:
        description: Provide scope in case you have tu install packages from the private NPM registry
        type: string
        required: false
      private-npm-registry-url:
        description: Url of the private registry
        type: string
        required: false
      should-lint-code:
        description: indicates whether lint the code
        type: boolean
        required: false
        default: true
      should-run-tests:
        description: indicates whether run tests
        type: boolean
        required: false
        default: true

    secrets:
      github-token:
        description: GitHub token to checkout repo
        required: true
      npm-token:
        description: NPM token to publish package
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: ${{ inputs.private-npm-registry-url }}
          scope: ${{ inputs.private-npm-registry-scope }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Run tests
        if: ${{ inputs.should-run-tests == true }}
        run: npm ${{ inputs.npm-script-name-test }}

      - name: Lint code
        if: ${{ inputs.should-lint-code == true }}
        run: npm run ${{ inputs.npm-script-name-lint }}

      - name: Transpile typescript sources
        run: npm run ts:validate
