name: Checkout common actions

on:
  workflow_call:
    inputs:
      private-npm-registry-scope:
        description: Provide scope in case you have tu install packages from the private NPM registry
        type: string
        required: false
      private-npm-registry-url:
        description: Url of the private registry
        type: string
        required: false

    secrets:
      github-token:
        description: GitHub token to checkout repo
        required: true
      npm-token:
        description: NPM token to publish package
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: ${{ inputs.private-npm-registry-url }}
          scope: ${{ inputs.private-npm-registry-scope }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Transpile typescript sources
        run: npm run ts:validate
