name: Validate commit messages
on:
  workflow_call:
    inputs:
      private-npm-registry-scope:
        description: Provide scope in case you have tu install packages from the private NPM registry
        type: string
        required: false
      private-npm-registry-url:
        description: Url of the private registry
        type: string
        required: false

    secrets:
      github-token:
        description: GitHub token to checkout repo
        required: true
      npm-token:
        description: NPM token to publish package
        required: false

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: ${{ inputs.private-npm-registry-url }}
          scope: ${{ inputs.private-npm-registry-scope }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Validate commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
