name: Checkout common actions

on:
  workflow_call:
    inputs:
      is-npm-package:
        required: false
        type: boolean
        default: false
      private-npm-registry-scope:
        description: Provide scope in case you have tu install packages from the private NPM registry
        type: string
        required: false
      private-npm-registry-url:
        description: Url of the private registry
        type: string
        required: false

    secrets:
      github-token:
        description: GitHub token to checkout repo
        required: true
      npm-token:
        description: NPM token to publish package
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.github-token }}

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: ${{ inputs.private-npm-registry-url }}
          scope: ${{ inputs.private-npm-registry-scope }}

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Build
        if: ${{ inputs.is-npm-package == true }}
        run: npm run ts

      # According to npm docs:
      # You can also provide a .npmignore file in the root of your package or in the subdirectories,
      # which will keep files from being included.
      # At the root of your package it will not override the "files" field, but in subdirectories it will.
      # .npmignore usually excludes test files. Therefore, we have to copy it to the subdirectory to make it works
      - name: Copy required assets to ./dist
        if: ${{ inputs.is-npm-package == true }}
        run: |
          cp .npmignore ./dist

      - name: Release new version
        run: npm run release
        env:
          NPM_TOKEN: ${{secrets.npm-token }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
