name: Shared terraform workflow

on:
  workflow_call:
    secrets:
      github-token:
        description: GitHub token to checkout repo
        required: true

    inputs:
      path:
        description: Path when the terraform files are located
        required: true
        type: string

jobs:
  lint:
    name: Setup Terraform and lint .tf files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}

      - name: Get Terraform version
        id: tf-version
        run: echo "TERRAFORM_VERSION=$(cat .tf-version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.tf-version.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Lint Terraform
        run: terraform fmt -recursive -check -diff ${{ inputs.path }}
